version: '3'

services:

    mosquitto:
        build:
          context: mosquitto/
        ports:
         - "1883:1883"
        restart: always
        volumes:
          - ./mosquitto/config:/opt/config
        command: mosquitto

    telegram_bot:
        build:
          context: telegram_bot/
        restart: always
        volumes:
          - ./telegram_bot/app-files:/opt/app
        command: python3 telegrambot.py
