version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.4.12
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
    volumes:
      - ./mqtt/config:/mqtt/config
    command: mosquitto -c /mqtt/config/mosquitto.conf
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
